language: ruby
before_install: gem install bundler -v 2.1.2
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
install:
  - bundle install --retry=3
script:
  - bundle exec rake test
  - bundle exec rake rubocop
